# Generated by Django 4.1.7 on 2023-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
