# Generated by Django 4.1.7 on 2023-03-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='pronouns',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
